name: Deploy Blazor App
on:
  push:
    branches:
      - main # Change this to your main branch name
jobs:
        build:
          runs-on: ubuntu-latest
      
          steps:
            - name: Checkout repository
              uses: actions/checkout@v2
      
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: '7.0.401' 
      
            - name: Build and Publish
              run: |
                dotnet build --configuration Release
                dotnet publish -c Release -o ./publish
                - name: Deploy to GitHub Pages
                uses: peaceiris/actions-gh-pages@v3
                with:
                  deploy_key: ${{ secrets.ACCESS_TOKEN }}
                  publish_dir: ./publish/wwwroot
                  publish_branch: gh-pages
        